name: Unstable Builds (Pushes)
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: chmod +x ./gradlew

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon

      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/